#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Wed Mar 18 13:36:31 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
from ftp import login,quit,getFile,upFile,listFiles

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("Host Address:"))
        self.txtHostAddress = wx.TextCtrl(self, wx.ID_ANY, "")
        self.btnConnect = wx.Button(self, wx.ID_ANY, _("Connect..."))
        self.list_ctrl_1 = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.btnUpload = wx.Button(self, wx.ID_ANY, _("Upload File..."))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.TextHandler, self.txtHostAddress)
        self.Bind(wx.EVT_BUTTON, self.Conn, self.btnConnect)
        self.Bind(wx.EVT_BUTTON, self.FileUpload, self.btnUpload)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Main Window"))
        self.SetSize((600, 300))
        self.txtHostAddress.SetMinSize((280, 27))
        self.btnUpload.SetMinSize((300, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.txtHostAddress, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.btnConnect, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND | wx.SHAPED, 0)
        sizer_3.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 8, wx.EXPAND, 0)
        sizer_4.Add(self.btnUpload, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def TextHandler(self, event):  # wxGlade: MyFrame.<event_handler>
	# end wxGlade
        self.address = event.GetString()

    def Conn(self, event):  # wxGlade: MyFrame.<event_handler>
	# end wxGlade
	    if not self.address:
		    wx.MessageBox('Please enter address first')
		    return
	    user = wx.TextEntryDialog(None,'Enter username','Login','')
	    if user.ShowModal() == wx.ID_OK:
		    self.user = user.GetValue()
		    pwd = wx.TextEntryDialog(None,'Enter password','Login','')
		    if pwd.ShowModal() == wx.ID_OK:
			    self.pwd = pwd.GetValue()
		    if not self.pwd or not self.user:
			    wx.MessageBox('username/password cannot be blank')
			    return
	    if login(self.address, self.user, self.pwd) == False:
		    wx.MessageBox('Check login credentials')
		    return
	    else:
			wx.MessageBox('Login Successful')

    def FileUpload(self, event):  # wxGlade: MyFrame.<event_handler>
        # end wxGlade
	#global user,pwd
        filename = ''
        dlg = wx.FileDialog(self, message="Choose a file", style=wx.FD_SAVE)
        if dlg.ShowModal() == wx.ID_OK:
	        filename = dlg.GetPath()
        dlg.Destroy()
        if not filename:
		   return
        login(self.address,self.user,self.pwd)
        upFile(filename)
        quit()

# end of class MyFrame
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    gettext.install("FTP_Client") # replace with the appropriate catalog name

    FTP_Client = MyApp(0)
    FTP_Client.MainLoop()
