#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Mar 17 17:12:10 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

from ftp import login,quit,getFile,upFile,listFiles,GetCurrentDir,SetCurrentDir,deleteFile,deleteDir
class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        # self.SetClientSize(wx.Size(300,300))
        self.deleteDir = wx.Button(self, wx.ID_ANY, _("Delete Directory"))
        self.deleteFile = wx.Button(self, wx.ID_ANY, _("Delete File"))
        self.list_box = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.findFilesBtn = wx.Button(self, wx.ID_ANY, _("Find Files"))
        self.deleteBtn = wx.Button(self, wx.ID_ANY, _("Delete"))
        self.findFilesBtn.Bind(wx.EVT_BUTTON, self.ButtonToLoad)
        self.list_box.Bind(wx.EVT_LISTBOX_DCLICK, self.ViewDir)
        self.deleteBtn.Bind(wx.EVT_BUTTON, self.DeleteItem)

        self.__set_properties()
        self.__do_layout()

        login()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.deleteDir, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.deleteFile, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.list_box, 0, wx.EXPAND, 0)
        sizer_1.Add(self.findFilesBtn, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.deleteBtn, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def showFiles(data):
        for x in data:
            self.list_box.Append(x)

    def ButtonToLoad(self, event):
        data = listFiles()

        showFiles(data)

    def ViewDir(self, event):
        currDir = GetCurrentDir()
        print currDir
        SetCurrentDir(self.list_box.GetStringSelection())
        print self.list_box.GetStringSelection()
        GetCurrentDir()

        self.list_box.Clear()

        data = listFiles()
        showFiles(data)


    def DeleteItem(self, event):
        item = self.list_box.GetStringSelection()

        if item.find('.') != -1:
            deleteFile(item)
        else:
            deleteDir(item)

        self.list_box.Clear()
        data = listFiles()
        showFiles(data)

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()